Feature/profile
Peaksoft-Moscow/giftlist.m5 pull request #25
Opened 2023-07-25 16:25 UTC by AnaraAlmazova

Update  profile

2023-07-26 20:32 UTC, MamatisaevaNurisa commented on src/main/java/com/peaksoft/giftlistm5/model/User.java
> +        return getUserInfo();
I am not sure, but I think here return UserInfo not getUserInfo.

2023-07-26 20:32 UTC, MamatisaevaNurisa commented on src/main/java/com/peaksoft/giftlistm5/model/UserInfo.java
> +
Remove extra lines

2023-07-26 20:32 UTC, MamatisaevaNurisa commented on src/main/java/com/peaksoft/giftlistm5/service/UserProfileService.java
> +
remove lines

2023-07-26 20:32 UTC, MamatisaevaNurisa commented on src/main/java/com/peaksoft/giftlistm5/service/UserProfileService.java
> +
method convertToResponse and getFullInfoMyProfile return the same value.

2023-07-27 07:04 UTC, Khaadikg commented on src/main/java/com/peaksoft/giftlistm5/service/UserProfileService.java
> +            Shoes shoes = Shoes.FORTY_ONE;
Default value должно ли быть 41?

2023-07-27 07:06 UTC, Khaadikg commented on src/main/java/com/peaksoft/giftlistm5/service/UserProfileService.java
> +        if (user.getPassword().equals(encoder.encode(oldPassword))) {
Нужна проверка на OldPassword = repostitoryGetOldPassword

2023-07-27 07:09 UTC, Khaadikg requested changes
Fine

2023-08-08 15:16 UTC, merged